<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptAsset extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima9');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}
	
	public function index()
	{
		//$akunKas=$this->divTreeKas($this->common_model->comboGetrptAsset()->result_array(), '1-1100');
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Perubahan Aset Kelolaan</a></li>');
		$this->template->set('pagetitle','Filter Laporan Perubahan Aset Kelolaan');		
		//$data['akunKas'] = $akunKas;
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="aset";
		$data["action"]="rptAsset/result";
		$this->template->load('default','freport/filter',$data);
	}
	
	
	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
			$wilayah=$arr[4];
					
			
		}else{
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
			$sesLogin=$this->input->post('sesLogin');
			if ($sesLogin=='center'){
					$wilayah=$this->input->post('wilayah');
			}else{
				$wilayah=$this->session->userdata('auth')->ID_CABANG;
			}
			
		}
		
		$data['sesLogin']=$sesLogin;
		$data['wilayah']=$wilayah;
		
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$data['nmcabang']=$rsCab;

		$title='Laporan Perubahan Aset '.$rsCab->KOTA.' '.$blnStr[$bln]." ".$thn;
		$data['title']=$title;
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;		
		$data['strBulan']=$blnStr[$bln];

		$namafile="lapAsset_".$rsCab->KOTA.$thn.$bln;
		if ($display==0){
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayAsset',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayAsset', $data, true);
			$html.=$footer;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'landscape');
		}

	}


	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
		if ($sesLogin=='center'){
			$wilayah=$arr[4];
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$nmcabang=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();

		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);

		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Laporan Perubahan Aset Kelolaan '.$nmcabang->KOTA.' Bulan '.$blnStr[$bln]." ".$thn;
		$namafile="lapPerubahanAset_".$nmcabang->KOTA.$thn.$bln;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);
		$objDrawing->setHeight(60);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		
		// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle('Lap_PerubahanAset'.$nmcabang->KOTA.$thn.$bln);
		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl : '.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		$setHeaderRow=array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				);

//ISI
$row=5;
$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'NO')
			->setCellValue('C'.$row, 'Nama')
			->setCellValue('F'.$row, 'Tgl Perolehan')
			->setCellValue('G'.$row, 'Nilai Perolehan Total')
			->setCellValue('H'.$row, 'Nilai Perolehan Saat Seting')
			->setCellValue('I'.$row, 'Lama Susut s.d Periode Pilih')
			->setCellValue('J'.$row, 'Lama Sisa Susut')
			->setCellValue('K'.$row, 'Susut @bulan')
			->setCellValue('L'.$row, 'Akumulasi Susut')
			->setCellValue('M'.$row, 'Nilai Buku')
			->setCellValue('N'.$row, 'Status');
$objPHPExcel->getActiveSheet()->mergeCells('C'.$row.':E'.$row);
$objPHPExcel->getActiveSheet()->getStyle('B'.$row.':N'.$row)->applyFromArray($setHeaderRow);
$row++;
	
$str="select * from ak_rekeningperkiraan where level=3 and idparent='1.2' and status=1 order by idacc";
$query=$this->db->query($str)->result();

if (sizeof($query )<=0){
	$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Rekening Fixed Asset tidak ada');
	$row++;
}else{
	$k=1;
	foreach ($query as $level3){
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $k)->setCellValue('C'.$row, $level3->nama);	
		$row++;

		$str4="select * from ak_rekeningperkiraan where idparent='".$level3->idacc."' and id_cab=".$cab_pilih." and   upper(nama) not like '%AKUM%'  order by idacc";
		$query4 =$this->db->query($str4)->result();
		
		if (sizeof($query4 )<=0){
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Rekening Fixed Asset Level 4 tidak ada');
			$row++;
		}else{
			$j=1;
			foreach ($query4 as $level4){
				$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $k.".".$j)->setCellValue('D'.$row, $level4->idacc." - ".$level4->nama);	
				$row++;
				
				$str5="select * from ak_rekeningperkiraan where idparent='".$level4->idacc."' and   upper(nama) not like '%AKUM%'";
				$query5 =$this->db->query($str5)->result();
				if (sizeof($query5 )<=0){
					$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Rekening Fixed Asset Level 5 tidak ada');
					$row++;
				}else{
					$i=1;
					foreach ($query5 as $level5){
						$strSeting="select * from ak_fixed_asset_setting where accFixedAsset='".$level5->idacc."'";
						$resSeting= $this->db->query($strSeting)->row();
						if (sizeof($resSeting )<=0){
							$tglP="-";
							$NP_total=0;
							$NP_saat_ini=0;
							$lama_sd_saat_ini=0;
							$lama_sisa=0;
							$susut_bln=0;
							$akm=0;
							$nilaibuku=0;
							$sts='Belum di seting';
						}else{
							$strCek="select sum(jumlah) jml, count(*) cnt from jurnal where (idperkdebet='".$resSeting->accSusutAkm."' or idperkkredit='".$resSeting->accSusutAkm."') and sumber_data='susut' and concat(tahun,bulan)<='".$thn.$bln."' and status_validasi=1";
							$resCek= $this->db->query($strCek)->row();
							$cnt=0;
							if (sizeof($resCek )<=0){							
								$cnt=0;
							}else{								
								$cnt=$resCek->cnt;
							}

							//lama susut s.d saat ini =+ n kali jurnal, lama sisa - n kali jurnal
							$tglP=$resSeting->tgl_perolehan;							
							$NP_saat_ini=$resSeting->nilai_perolehan_saat_ini;
							$lama_sd_saat_ini = ($resSeting->lama_susut_sd_saat_ini + $cnt);
							$lama_sisa =( $resSeting->lama_sisa_susut - $cnt);
							$susut_bln=($resSeting->nilai_perolehan_saat_ini/$resSeting->lama_sisa_susut);							
							$akm=($susut_bln * $lama_sd_saat_ini);
							$NP_total=$susut_bln * ($lama_sd_saat_ini+$lama_sisa);							
							$nilaibuku=$NP_total-$akm;														
							$sts=($resSeting->isactive==1?"Asset Exist":"Asset dihapus");
						}
						
						$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $k.".".$j.".".$i)
												->setCellValue('E'.$row, $level5->idacc." - ".$level5->nama)
												->setCellValue('F'.$row, ($tglP=='-'?$tglP:strftime("%d %B %Y", strtotime($tglP))))
												->setCellValue('G'.$row, "Rp. ".number_format($NP_total,2,',','.') )
												->setCellValue('H'.$row, "Rp. ".number_format($NP_saat_ini,2,',','.') )
												->setCellValue('I'.$row, $lama_sd_saat_ini)
												->setCellValue('J'.$row, $lama_sisa)
												->setCellValue('K'.$row,  "Rp. ".number_format($susut_bln,2,',','.') )
												->setCellValue('L'.$row, "Rp. ".number_format($akm*-1,2,',','.') )
												->setCellValue('M'.$row, "Rp. ".number_format($nilaibuku,2,',','.') )
												->setCellValue('N'.$row, $sts);
						$row++;
						$i++;
					}
				}
				$j++;
			}
		}
		$k++;
	}
}


	$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B '.$title.' &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
	
	
}
