<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptCashFlow extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima7');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}	

	public function index()
	{
		//$akunKas=$this->divTreeKas($this->common_model->comboGetRptCashFlowAll()->result_array(), '1-1100');
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Arus Kas</a></li>');
		$this->template->set('pagetitle','Filter Cash Flow ');		
		//$data['akunKas'] = $akunKas;
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="cashflow";
		$data["action"]="rptCashFlow/result";
		$this->template->load('default','freport/filter',$data);
	}

	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
			if ($sesLogin=='center'){
				$wilayah=$arr[4];
			}
			
		}else{
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
			$sesLogin=$this->input->post('sesLogin');
			if ($sesLogin=='center'){
					$wilayah=$this->input->post('wilayah');
			}
			
		}
		
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;
 		$data['strBulan']=$blnStr[$bln];
		$data['sesLogin']=$sesLogin;
		if ($sesLogin=='center'){
			$data['wilayah']=$wilayah;
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$data['nmcabang']=$rsCab;
		$title='Laporan Cash Flow '.$rsCab->KOTA.' '.$blnStr[$bln]." ".$thn;
		$data['title']=$title;
		$namafile="cashflow_".$rsCab->KOTA.$thn.$bln;
		if ($display==0){
			$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Arus Kas</a></li>');
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayCashFlow',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayCashFlow', $data, true);
			$html.=$footer;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'landscape');
		}

	}
	
	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
		$thn=$arr[0];
		$bln=$arr[1];
		$display=$arr[2];			
		$sesLogin=$arr[3];
		if ($sesLogin=='center'){
				$wilayah=$arr[4];
		}
	
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		
		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Laporan Arus Kas '.$rsCab->KOTA.' Bulan '.$blnStr[$bln]."  ".$thn;
		$namafile="aruskas_".$rsCab->KOTA.$thn.$bln;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);
		$objDrawing->setHeight(70);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl :'.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		
		//$objPHPExcel->getActiveSheet()->setCellValue('B5', "[ ".$idacc." ] ".strtoupper($accName));
		// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle('CashFlow'.$thn.$bln);
		//header table
		$row=7;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'AKTIVITAS OPERASI');
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$row++;
		//ZIS (4.%)
		$nmcabang=$this->gate_db->query('select KOTA from mst_cabang where ID_CABANG='.$cab_pilih)->row();
		$ketcabang=($cab_pilih>1?'CABANG ':'').' '.(sizeof($nmcabang)>0?$nmcabang->KOTA:'');
		
		$str="select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkkredit in (select distinct idacc from ak_rekeningperkiraan where idacc like '4.%'  and id_cab=".$cab_pilih." and status=1 ) and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')";
		
		$rsJumlahZIS=$this->db->query($str)->row();
		$jumlah=$rsJumlahZIS->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Penerimaan Kas dari Pelanggan (ZIS :'.strtoupper($ketcabang).')')->setCellValue('D'.$row, 'Rp. '.number_format($jumlah,2,',','.') );
		$row++;
		
		//Biaya (5.%)
		$rsJumlahExpense=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1 and id_cab=".$cab_pilih." and idacc like '5.%' and upper(nama) not like '%PENYUSUTAN%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();

		$jumlah=$jumlah-$rsJumlahExpense->jml;		
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pembayaran Kas Kepada Pemasok dan Karyawan & Untuk Beban Usaha (Expenses)')->setCellValue('D'.$row, "( Rp. ".number_format($rsJumlahExpense->jml,2,',','.')." )" );
		$row++;
/**/
		$rsJumlahPiutangDiKredit=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkkredit in (SELECT DISTINCT idacc from ak_rekeningperkiraan WHERE (idacc LIKE '1.1.07%' OR idacc LIKE '1.1.08%' OR idacc LIKE '1.1.09%' OR idacc LIKE '1.1.10%' OR idacc LIKE '1.1.14%')  AND idacc NOT IN ( SELECT idacc from ak_rekeningperkiraan WHERE (idacc LIKE '1.1.01%' OR idacc LIKE '1.1.02%')) AND LEVEL >2 AND STATUS=1 AND id_cab=".$cab_pilih."  ) and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
		$jumlah=$jumlah+$rsJumlahPiutangDiKredit->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Penerimaan Pembayaran Piutang & Uang Muka')->setCellValue('D'.$row, "( Rp. ".number_format($rsJumlahPiutangDiKredit->jml,2,',','.')." )" );
		$row++;

		$rsJumlahPiutang=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkdebet in (SELECT DISTINCT idacc from ak_rekeningperkiraan WHERE (idacc LIKE '1.1.07%' OR idacc LIKE '1.1.08%' OR idacc LIKE '1.1.09%' OR idacc LIKE '1.1.10%' OR idacc LIKE '1.1.14%')  AND idacc NOT IN ( SELECT idacc from ak_rekeningperkiraan WHERE (idacc LIKE '1.1.01%' OR idacc LIKE '1.1.02%')) AND LEVEL >2 AND STATUS=1 AND id_cab=".$cab_pilih."  ) and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
		$jumlah=$jumlah-$rsJumlahPiutang->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pemberian Piutang & Uang Muka')->setCellValue('D'.$row, "( Rp. ".number_format($rsJumlahPiutang->jml,2,',','.')." )" );
		$row++;

/**/
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Kas dihasilkan dari Operasi')->setCellValue('E'.$row, ($jumlah<0?"( Rp. ".number_format($jumlah,2,',','.')." )":"Rp. ".number_format($jumlah,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('E'.$row)->getFont()->setBold(true);
		$row+=2;


		//Pendapatan lain (8-%)
		//$rsJumlahPL=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkkredit in (select distinct idacc from ak_rekeningperkiraan where   status=1  and id_cab=".$cab_pilih."  and idacc like '8-%') and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();

		//$jumlah=$jumlah+$rsJumlahPL->jml;
		//$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pendapatan (Beban) Di Luar Usaha')->setCellValue('D'.$row, 'Rp. '.number_format($rsJumlahPL->jml,2,',','.') );
		//$row++;

		//Biaya lain2 (9-%)
		//$rsJumlahExpenseOther=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1 and id_cab=".$cab_pilih."  and idacc like '9-%') and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();

		//$jumlahLain=$rsJumlahPL->jml-$rsJumlahExpenseOther->jml;
		//$jumlah=$jumlah-$rsJumlahExpenseOther->jml;
		//$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Beban Lain-lain')->setCellValue('D'.$row, "( Rp. ".number_format($rsJumlahExpenseOther->jml,2,',','.')." )" );
		//$row++;
		//$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Kas dihasilkan dari Lain-lain')->setCellValue('E'.$row, ($jumlahLain<0?"( Rp. ".number_format($jumlahLain,2,',','.')." )":"Rp. ".number_format($jumlahLain,2,',','.')) );
		//$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		//$objPHPExcel->getActiveSheet()->getStyle('E'.$row)->getFont()->setBold(true);
		//$row++;

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Jumlah Kas Bersih dari Aktivitas Operasi')->setCellValue('F'.$row, ($jumlah<0?"( Rp. ".number_format($jumlah,2,',','.')." )":"Rp. ".number_format($jumlah,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setBold(true);
		$row+=2;
		
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'AKTIVITAS INVESTASI');
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$row++;
		
		$rsJumlahModal=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkkredit in (select distinct idacc from ak_rekeningperkiraan where  status=1 and id_cab=".$cab_pilih."  and idacc like '3.%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
		$jumlah=$jumlah+$rsJumlahModal->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Penerimaan Investasi')->setCellValue('D'.$row, "Rp. ".number_format($rsJumlahModal->jml,2,',','.') );
		$row++;
/**/
$rsJumlahJualAset=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkkredit in (select distinct idacc from ak_rekeningperkiraan where  status=1 and id_cab=".$cab_pilih."  and idacc like '1.2.01%' and upper(nama) not like '%AKUM%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
$jumlah=$jumlah+$rsJumlahJualAset->jml;
$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Penjualan Asset')->setCellValue('D'.$row, "Rp. ".number_format($rsJumlahJualAset->jml,2,',','.') );
		$row++;

/**/
		
		$rsJumlahBeliAset=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1  and id_cab=".$cab_pilih."  and idacc like '1.2.01%' and upper(nama) not like '%AKUM%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
		$jumlah=$jumlah-$rsJumlahBeliAset->jml;
		$jumlahInvestasi=$rsJumlahModal->jml-$rsJumlahBeliAset->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pembelian Semua Aset Bersih')->setCellValue('D'.$row, "( Rp. ".number_format($rsJumlahBeliAset->jml,2,',','.').")" );
		$row++;


/**/
$rsJumlahKeluarInvestasi=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1  and id_cab=".$cab_pilih."  and idacc like '1.2.03%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
$jumlah=$jumlah-$rsJumlahKeluarInvestasi->jml;
$jumlahInvestasi=($rsJumlahModal->jml+$rsJumlahJualAset->jml)-($rsJumlahBeliAset->jml+$rsJumlahKeluarInvestasi->jml);
$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pengeluaran Investasi')->setCellValue('D'.$row, "Rp. ".number_format($rsJumlahKeluarInvestasi->jml,2,',','.') );
		$row++;

/**/

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Jumlah Kas Bersih dari Aktivitas Investasi')->setCellValue('F'.$row,  ($jumlahInvestasi<0?"( Rp. ".number_format($jumlahInvestasi,2,',','.')." )":"Rp. ".number_format($jumlahInvestasi,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setBold(true);
		$row+=2;

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'AKTIVITAS PENDANAAN');
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$row++;

/**/
$rsJumlahTerimaHutang=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkkredit in (select distinct idacc from ak_rekeningperkiraan where  status=1  and id_cab=".$cab_pilih."  and idacc like '2.%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
$jumlah=$jumlah+$rsJumlahTerimaHutang->jml;
$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Penerimaan Liabilitas/Hutang')->setCellValue('D'.$row,  "( Rp. ".number_format($rsJumlahTerimaHutang->jml,2,',','.').")" );
		$row++;

		$rsJumlahHutang=$this->db->query("select ifnull(sum(jumlah),0) jml from ak_jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where  status=1  and id_cab=".$cab_pilih."  and idacc like '2.%') and bulan='$bln' and tahun='$thn' and status_validasi=1 and  ( isjurnalbalik='off' or isjurnalbalik='0')")->row();
		$jumlah=$jumlah-$rsJumlahHutang->jml;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pembayaran Liabilitas/Hutang ')->setCellValue('D'.$row,  "( Rp. ".number_format($rsJumlahHutang->jml,2,',','.').")" );
		$row++;

$aktPendanaan=($rsJumlahTerimaHutang->jml)-($rsJumlahHutang->jml);
		
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Jumlah Kas Bersih dari Aktivitas Pendanaan')->setCellValue('F'.$row, ($aktPendanaan<0?"( Rp. ".number_format($aktPendanaan,2,',','.')." )":"Rp. ".number_format($aktPendanaan,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setBold(true);
		$row+=2;

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'KENAIKAN (PENURUNAN) NETO DALAM KAS DAN SETARA KAS')->setCellValue('G'.$row,  ($jumlah<0?"( Rp. ".number_format($jumlah,2,',','.')." )":"Rp. ".number_format($jumlah,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('G'.$row)->getFont()->setBold(true);
		$row++;

		$initval=$this->report_model->getInitValCashFlow();
		$saldoLalu=$this->report_model->getSaldoLaluCashFlow($bln, $thn, $cab_pilih);
		$jumlahAwal=$initval+$saldoLalu;
		$saldoAkhir=$jumlah+$jumlahAwal;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'KAS DAN SETARA KAS PADA AWAL BULAN')->setCellValue('G'.$row,  ($jumlahAwal<0?"( Rp. ".number_format($jumlahAwal,2,',','.')." )":"Rp. ".number_format($jumlahAwal,2,',','.')) );
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('G'.$row)->getFont()->setBold(true);
		$row++;

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'KAS DAN SETARA KAS PADA AKHIR BULAN')->setCellValue('G'.$row,  ($saldoAkhir<0?"( Rp. ".number_format($saldoAkhir,2,',','.')." )":"Rp. ".number_format($saldoAkhir,2,',','.')) );
		
		$objPHPExcel->getActiveSheet()->mergeCells("C".$row.":F".$row);
		$objPHPExcel->getActiveSheet()->getStyle("C".$row.":G".$row)->applyFromArray(
		array(
			'font'    => array(
				'bold'      => true
			),
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			),
			'borders' => array(
				'allborders'     => array(
 					'style' => PHPExcel_Style_Border::BORDER_THIN,
					'color' => array('argb' => '000000')
 				)				
			),
			'fill' => array(
	 			'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
	  			'rotation'   => 90,
	 			'startcolor' => array(
	 				'argb' => 'FFA0A0A0'
	 			),
	 			'endcolor'   => array(
	 				'argb' => 'FFFFFFFF'
	 			)
	 		)
		)
		);
		$row++;

		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B $title &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
	
	
}
