<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptPendapatanZIS extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima5');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}	

	public function index()
	{
		//$akunKas=$this->divTreeKas($this->common_model->comboGetrptPendapatanZISAll()->result_array(), '1-1100');
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Pendapatan Penghimpunan</a></li>');
		$this->template->set('pagetitle','Filter Laporan Pendapatan ZIS');		
		//$data['akunKas'] = $akunKas;
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="realisasi";
		$data["action"]="rptPendapatanZIS/result";
		$this->template->load('default','freport/filter',$data);
	}

	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
			if ($sesLogin=='center'){
				$wilayah=$arr[4];
			}
			
		}else{
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
			$sesLogin=$this->input->post('sesLogin');
			if ($sesLogin=='center'){
					$wilayah=$this->input->post('wilayah');
			}
			
		}
		
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;
 		$data['strBulan']=$blnStr[$bln];
		$data['sesLogin']=$sesLogin;
		if ($sesLogin=='center'){
			$data['wilayah']=$wilayah;
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$data['nmcabang']=$rsCab;
		$data['strbulan']=$blnStr[$bln];
		$title='Laporan Pendapatan ZIS '.$rsCab->KOTA.' '.$blnStr[$bln]." ".$thn;
		$data['title']=$title;
		$namafile="realisasi_".$rsCab->KOTA.$thn.$bln;
		if ($display==0){
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayPendapatanZIS',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayPendapatanZIS', $data, true);
			$html.=$footer;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'landscape');
		}

	}
	
	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
		$thn=$arr[0];
		$bln=$arr[1];
		$display=$arr[2];			
		$sesLogin=$arr[3];
		if ($sesLogin=='center'){
				$wilayah=$arr[4];
		}
	
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		
		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Laporan Pendapatan ZIS '.$rsCab->KOTA.' Bulan '.$blnStr[$bln]."  ".$thn;
		$namafile="pendapatanZis_".$rsCab->KOTA.$thn.$bln;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);	//**
		$objDrawing->setHeight(70);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl :'.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		$setHeaderRow=array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				);

		$objPHPExcel->getActiveSheet()->setTitle('realisasi'.$thn.$bln);
		//header table

		//isi

		$row=5;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'NAMA CABANG '.strtoupper($rsCab->KOTA));
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'PERIODE '.$blnStr[$bln]."  ".$thn);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		
		$row+=2;
		$str="select * from ak_rekeningperkiraan WHERE id_cab=".$cab_pilih." and status=1 and idacc like '4.%' and level=5 order by nama";
		$rsZIS=$this->db->query($str)->result();

		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Pendapatan ')->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Pendapatan Dana')->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$row++;

		if (sizeof ($rsZIS)<=0){
			$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, 'Rekening Perkiraan Pendapatan ZIS Tidak ada atau bukan data Cabang Anda');
			$row++;
		}else{
			$jumTotl=0;
			foreach ($rsZIS as $detil){
				$strJumlah="SELECT ifnull(SUM(jumlah),0) jmlzis from ak_jurnal WHERE sumber_data IN ('tsetoranzis','tinsidentil')  AND jenis='BKM' AND idperkkredit ='". $detil->idacc."' and status_validasi=1 and bulan='$bln' and tahun='$thn' and  ( isjurnalbalik='off' or isjurnalbalik='0')";
				$rsJmlZIS=$this->db->query($strJumlah)->row();
				
				if ($rsJmlZIS->jmlzis>0){
					$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detil->nama)->setCellValue('E'.$row, "Rp. ".number_format($rsJmlZIS->jmlzis,2,',','.'));
					$row++;
				}
				$jumTotl+=$rsJmlZIS->jmlzis;
			}
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Total Pendapatan Dana')->getStyle('C'.$row)->getFont()->setSize(14);
			$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->setCellValue('F'.$row, "Rp. ".number_format($jumTotl,2,',','.'))->getStyle('F'.$row)->getFont()->setSize(14);
			$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setBold(true);
			$row++;
			
		}


		//setor ke pusat


		$idrk_pusat=(strlen($cab_pilih)>1?'2.1.03.':'2.1.03.0').$cab_pilih.'.02';		
		$strSetor="SELECT ifnull(SUM(jumlah),0) jmlsetor FROM ak_jurnal WHERE sumber_data IN ('tsetoranzis','tinsidentil') AND idperkdebet IN(SELECT idacc from ak_rekeningperkiraan WHERE idacc = '$idrk_pusat') and status_validasi=1 and bulan='$bln' and tahun='$thn' and  ( isjurnalbalik='off' or isjurnalbalik='0')";
		$rsSetor=$this->db->query($strSetor)->row();
		$harusSetor=$jumTotl-$rsSetor->jmlsetor;
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Setoran Ke Pusat')->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Ditransfer langsung ke rek Pusat')->setCellValue('F'.$row, "Rp. ".number_format($rsSetor->jmlsetor,2,',','.'))->getStyle('F'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setUnderline(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Sisa yang harus disetor ke Pusat')->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->setCellValue('F'.$row, "Rp. ".number_format($harusSetor,2,',','.'))->getStyle('F'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->getStyle('F'.$row)->getFont()->setSize(14);

		$row+=3;		
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, strtoupper($rsCab->KOTA).", ".strftime('%d %B %Y'));
		$row+=2;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Disusun Oleh")->setCellValue('F'.$row, "Mengetahui");
		$row+=4;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "(              )")->setCellValue('F'.$row, "(              )");
		
		//END OF ISI

		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B $title &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
	
	
}
