<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptPerubahanDana extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima8');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}
	
	public function index()
	{
		//$akunKas=$this->divTreeKas($this->common_model->comboGetrptPerubahanDana()->result_array(), '1-1100');
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Perubahan Dana</a></li>');
		$this->template->set('pagetitle','Filter Laporan Perubahan Dana');		
		//$data['akunKas'] = $akunKas;
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="perubahanDana";
		$data["action"]="rptPerubahanDana/result";
		$this->template->load('default','freport/filter',$data);
	}
	
	
	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
			if ($sesLogin=='center'){
				$wilayah=$arr[4];
			}			
			
		}else{
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
			$sesLogin=$this->input->post('sesLogin');
				if ($sesLogin=='center'){
					$wilayah=$this->input->post('wilayah');
				}else{
					$wilayah=$this->session->userdata('auth')->ID_CABANG;
				}
			
		}
		
		$data['sesLogin']=$sesLogin;
		$data['wilayah']=$wilayah;
		
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$data['nmcabang']=$rsCab;


		$title='Laporan Perubahan Modal/Ekuitas '.$rsCab->KOTA.' '.$blnStr[$bln]." ".$thn;
		$data['title']=$title;
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;		
		$data['strBulan']=$blnStr[$bln];

		$namafile="ekuitas_".$rsCab->KOTA.$thn.$bln;
		if ($display==0){
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayPerubahanDana',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayPerubahanDana', $data, true);
			$html.=$footer;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'portrait');
		}

	}
	
	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$strBulan=$blnStr[$bln];
		$sesLogin=$arr[3];
		if ($sesLogin=='center'){
			$wilayah=$arr[4];
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$nmcabang=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();

		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);

		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Laporan Perubahan Dana '.$nmcabang->KOTA.' Bulan '.$blnStr[$bln]." ".$thn;
		$namafile="laPerubahanDana_".$nmcabang->KOTA.$thn.$bln;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);
		$objDrawing->setHeight(60);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		
		// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle($nmcabang->KOTA.$thn.$bln);
		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl : '.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		$setHeaderRow=array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				);

		//ISI
		$row=5;
		$str="SELECT `idacc`, `nama`, `kelompok`, `level`,idparent, IF(`kelompok`='A','Aktiva','Pasiva') AS jenis
		FROM ak_rekeningperkiraan 
		WHERE  `kelompok` = 'M' AND `level`=2 and status=1 
		ORDER BY  `kelompok`,idacc";
		$query=$this->db->query($str)->result();
		$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, 'PERKIRAAN')->setCellValue('H'.$row, 'JUMLAH');
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row.':H'.$row)->applyFromArray($setHeaderRow);
		$row++;

	$i=1;
	$jenis="";
	$jumlah=array();	
	$jumlahP=0;
	$jumlahB=0;
	$saldoAkhir=0;	
	
	foreach ($query as $level2){	//idacc kel M level 2	
		$digitZis=substr($level2->idacc,2,1);
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $level2->idacc." - ".strtoupper($level2->nama))->getStyle('F'.$row)->getFont()->setBold(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Penerimaan")->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;
			
		
		//level 3
		$strPL3="select * from ak_rekeningperkiraan where idparent='4.".$digitZis."' and level=3 order by  idacc";	
		$resListPL3= $this->db->query($strPL3)->result();
		if (sizeof ($resListPL3)<=0){
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Rekening Perkiraan Pendapatan ZIS Tidak ada atau bukan data Cabang Anda");
			$row++;
		}else{	
			$jumlahPLevel3=0;
			$saldolAwal=0;
			foreach ($resListPL3 as $detilPL3){
				$strP="SELECT ifnull(SUM(jumlah),0) AS hasilP FROM ak_jurnal WHERE idperkkredit IN (SELECT DISTINCT idacc FROM ak_rekeningperkiraan WHERE   kelompok='P' and idacc like '".$detilPL3->idacc.".%' and id_cab=$cab_pilih) and status_validasi=1 and (concat(tahun,bulan) = '".$thn.$bln."' ) and  ( isjurnalbalik='off' or isjurnalbalik='0')";
				$queryP=$this->db->query($strP)->row();
				$jumlahP+=$queryP->hasilP;
				$jumlahPLevel3+=$queryP->hasilP;
				$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detilPL3->nama)->setCellValue('G'.$row, "Rp. ".number_format($queryP->hasilP,2,',','.'));
				$row++;
				
			}
		}
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Jumlah Penerimaan")->setCellValue('H'.$row, "Rp. ".number_format($jumlahPLevel3,2,',','.'))->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;
		
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Penyaluran")->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;
		
		//level 3
		$strBL3="select * from ak_rekeningperkiraan where idparent='5.".$digitZis."' and level=3 order by  idacc";	
		$resListBL3= $this->db->query($strBL3)->result();
		if (sizeof ($resListBL3)<=0){
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Rekening Perkiraan Biaya/Penyaluran Tidak ada atau bukan data Cabang Anda");
		
		}else{		
			$jumlahBLevel3=0;
			foreach ($resListBL3 as $detilBL3){				
				//value level 5 
				$strB="SELECT ifnull(SUM(jumlah),0) AS hasilB FROM ak_jurnal WHERE idperkdebet IN (SELECT DISTINCT idacc FROM ak_rekeningperkiraan WHERE   kelompok='B' and idacc like '".$detilBL3->idacc.".%' and id_cab=$cab_pilih) and status_validasi=1 and (concat(tahun,bulan) = '".$thn.$bln."' ) and  ( isjurnalbalik='off' or isjurnalbalik='0')";
				$queryB=$this->db->query($strB)->row();
				$jumlahB+=$queryB->hasilB;
				$jumlahBLevel3+=$queryB->hasilB;
				$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detilBL3->nama)->setCellValue('G'.$row, "Rp. ".number_format($queryB->hasilB,2,',','.'));
				$row++;			
				
			}
		}
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Jumlah Penyaluran")->setCellValue('H'.$row, "Rp. ".number_format($jumlahBLevel3,2,',','.'))->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;

		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Surplus (Defisit)")->setCellValue('H'.$row, "Rp. ".number_format(($jumlahPLevel3-$jumlahBLevel3),2,',','.'))->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;

		//saldo awal akun M
		$strInitM="select ifnull(sum(initval),0) saldo from ak_rekeningperkiraan where level=5 and  idacc  in (select idacc from ak_rekeningperkiraan where idacc like '".$level2->idacc.".%' and id_cab=$cab_pilih) ";	//ZISAW
		$queryInitM=$this->db->query($strInitM)->row();
		$InitM=$queryInitM->saldo;
		
		//+ jurnal sblm periode pilih
		$strPLalu="SELECT ifnull(SUM(jumlah),0) AS hasilP FROM ak_jurnal WHERE idperkkredit IN (SELECT DISTINCT idacc FROM ak_rekeningperkiraan WHERE   kelompok='P' and idacc like '4.".$digitZis.".%' and id_cab=$cab_pilih) and status_validasi=1 and (concat(tahun,bulan) < '".$thn.$bln."' ) and  ( isjurnalbalik='off' or isjurnalbalik='0')";
		$queryPLalu=$this->db->query($strPLalu)->row();
		$jmlLaluP=$queryPLalu->hasilP;

		
		//+ jurnal sblm periode pilih
		$strBLalu="SELECT ifnull(SUM(jumlah),0) AS hasilB FROM ak_jurnal WHERE idperkdebet IN (SELECT DISTINCT idacc FROM ak_rekeningperkiraan WHERE   kelompok='B' and idacc like '5.".$digitZis.".%' and id_cab=$cab_pilih) and status_validasi=1 and (concat(tahun,bulan) < '".$thn.$bln."' ) and  ( isjurnalbalik='off' or isjurnalbalik='0')";
		$queryBLalu=$this->db->query($strBLalu)->row();
		$jmlLaluB=$queryBLalu->hasilB;
		
		$saldolAwal=($InitM+$jmlLaluP) - $jmlLaluB;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "SALDO AWAL")->setCellValue('H'.$row, "Rp. ".number_format($saldolAwal,2,',','.'))->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row++;
				
		$saldo=$saldolAwal+($jumlahPLevel3-$jumlahBLevel3);
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "SALDO AKHIR")->setCellValue('H'.$row, "Rp. ".number_format($saldo,2,',','.'))->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
		$row+=2;
		
		$saldoAkhir+=$saldo;
		$i++;	

	}
	
	
	$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Jumlah Saldo Dana Zakat, Infaq/Shadaqoh, Amil, wakaf  s.d Periode ".$blnStr[$bln]." ".$thn)->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->setCellValue('H'.$row, number_format($saldoAkhir,2,',','.') )->getStyle('B'.$row.':H'.$row)->getFont()->setBold(true);
	$row+=2;

	


		//END ISI
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B '.$title.' &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
}
