<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptRealisasi extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima6');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}	

	public function index()
	{
		//$akunKas=$this->divTreeKas($this->common_model->comboGetrptRealisasiAll()->result_array(), '1-1100');
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Realisasi Anggaran Cabang</a></li>');
		$this->template->set('pagetitle','Filter Laporan Realisasi Anggaran');		
		//$data['akunKas'] = $akunKas;
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="realisasi";
		$data["action"]="rptRealisasi/result";
		$this->template->load('default','freport/filter',$data);
	}

	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];			
			$sesLogin=$arr[3];
			if ($sesLogin=='center'){
				$wilayah=$arr[4];
			}
			
		}else{
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
			$sesLogin=$this->input->post('sesLogin');
			if ($sesLogin=='center'){
					$wilayah=$this->input->post('wilayah');
			}
			
		}
		
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;
 		$data['strBulan']=$blnStr[$bln];
		$data['sesLogin']=$sesLogin;
		if ($sesLogin=='center'){
			$data['wilayah']=$wilayah;
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$data['nmcabang']=$rsCab;
		$data['strbulan']=$blnStr[$bln];
		$title='Laporan Realisasi Anggaran<br>'.$rsCab->KOTA.' '.$blnStr[$bln]." ".$thn;
		$data['title']=$title;
		$namafile="realisasi_".$rsCab->KOTA.$thn.$bln;
		if ($display==0){
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayRealisasi',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayRealisasi', $data, true);
			$html.=$footer;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'landscape');
		}

	}
	
	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
		$thn=$arr[0];
		$bln=$arr[1];
		$display=$arr[2];			
		$sesLogin=$arr[3];
		if ($sesLogin=='center'){
				$wilayah=$arr[4];
		}
	
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$rsCab=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		
		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Laporan Realisasi Anggaran '.$rsCab->KOTA.' Bulan '.$blnStr[$bln]."  ".$thn;
		$namafile="realisasi_".$rsCab->KOTA.$thn.$bln;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);
		$objDrawing->setHeight(70);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl :'.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
		$setHeaderRow=array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				);

		$objPHPExcel->getActiveSheet()->setTitle('realisasi'.$thn.$bln);
		//header table

		//isi

		$row=5;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'NAMA CABANG '.strtoupper($rsCab->KOTA));
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'PERIODE '.$blnStr[$bln]."  ".$thn);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
		
		$row+=2;


$str="select ifnull(sum(jumlah),0) jml from jurnal WHERE id_cab=".$cab_pilih." AND isanggaran='on' AND periodanggaran='".$thn.$bln."' and status_validasi=1";
$rsAngg=$this->db->query($str)->row();
$jumlahAnggaran=$rsAngg->jml;
//error disini krn problem akun pusat-cabang

$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Anggaran Yayasan Nurul Hayat Pusat ')->getStyle('B'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
$row++;
$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Hutang Afiliasi dari Pusat')->setCellValue('G'.$row, "Rp. ".number_format($jumlahAnggaran,2,',','.'));
$row++;
$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, 'Total Subsidi')->getStyle('C'.$row)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->setCellValue('H'.$row, "Rp. ".number_format($jumlahAnggaran,2,',','.'))->getStyle('H'.$row)->getFont()->setBold(true);
$row+=2;

$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'REALISASI BIAYA ')->getStyle('B'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
$row++;

//level 2 = header
	$strL2="select * from ak_rekeningperkiraan where level=2 and kelompok='B' AND idacc<>'9-1000'  order by  idacc";	
	$resList= $this->db->query($strL2)->result();	
	$jmlExpense=0;
	
	foreach ($resList as $detil){
		$jmlLvl2=0;
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $detil->nama)->getStyle('C'.$row)->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
		$row++;

		//echo "<tr><td>&nbsp;</td><td colspan=4><b>".$detil->nama."</b></td><td colspan=3>&nbsp;</td></tr>";
		$strL3="select * from ak_rekeningperkiraan where idparent='".$detil->idacc."' and kelompok='B' and upper(nama) not like '%PENYUSUTAN%' order by  idacc";			
		$resListL3= $this->db->query($strL3)->result();
		//echo "<tr><td colspan=7>$strL3</td></tr>";
		foreach ($resListL3 as $detilL3){
			$jmlAkumL3=0;
			$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detilL3->nama);
			$row++;			
			$strL4="select * from ak_rekeningperkiraan where idparent='".$detilL3->idacc."' and upper(nama) not like '%PENYUSUTAN%' and id_cab=".$cab_pilih."  order by  idacc";
			$resListL4= $this->db->query($strL4)->result();			
								
				foreach ($resListL4 as $detilL4){
					//biaya ada level max 4
					$strCekMax4="select count(*) jcek from ak_rekeningperkiraan where idparent='".$detilL4->idacc."'   and id_cab=".$cab_pilih."  order by  idacc";
					$resCekMax4= $this->db->query($strCekMax4)->row();
					if ($resCekMax4->jcek>0){

						$objPHPExcel->getActiveSheet()->setCellValue('E'.$row, $detilL4->nama);
						$row++;
						$strL5="select * from ak_rekeningperkiraan where idparent='".$detilL4->idacc."' and upper(nama) not like '%PENYUSUTAN%'  order by  idacc";
						$resListL5= $this->db->query($strL5)->result();
						$i=1;
						foreach ($resListL5 as $detilL5){
							$rsJumlahDebet=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet ='".$detilL5->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
							$rsJumlahKredit=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkkredit ='".$detilL5->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
							$jumlahbiaya=($rsJumlahDebet->jml) - $rsJumlahKredit->jml;
							if ($jumlahbiaya > 0){
								$objPHPExcel->getActiveSheet()->setCellValue('E'.$row,$i)->setCellValue('F'.$row, $detilL5->nama)->setCellValue('G'.$row, "Rp. ".number_format($jumlahbiaya,2,',','.'));
								$row++;	
								$jmlAkumL3+=$jumlahbiaya;
								$jmlExpense+=$jumlahbiaya;					
						
								$i++;
							}
						}
						$jmlLvl2+=$jmlAkumL3;
					}else{

						
						$row++;						
						$rsJumlahDebet=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet ='".$detilL4->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
						$rsJumlahKredit=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkkredit ='".$detilL4->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
						$jumlahbiaya=($rsJumlahDebet->jml) - $rsJumlahKredit->jml;
							if ($jumlahbiaya > 0){
								$objPHPExcel->getActiveSheet()->setCellValue('E'.$row,$i)->setCellValue('F'.$row, $detilL4->nama)->setCellValue('G'.$row, "Rp. ".number_format($jumlahbiaya,2,',','.'));
								$row++;	
								$jmlAkumL3+=$jumlahbiaya;
								$jmlExpense+=$jumlahbiaya;					
						
								$i++;
							}
						$jmlLvl2+=$jmlAkumL3;
					}
				}
				//$jmlLvl2+=$jmlAkumL3;
				$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, "Total ".$detilL3->nama)->getStyle('D'.$row)->getFont()->setSize(14);
				$objPHPExcel->getActiveSheet()->getStyle('D'.$row)->getFont()->setBold(true);
				$objPHPExcel->getActiveSheet()->setCellValue('G'.$row, "Rp. ".number_format($jmlAkumL3,2,',','.'))->getStyle('G'.$row)->getFont()->setSize(14);
				$objPHPExcel->getActiveSheet()->getStyle('G'.$row)->getFont()->setBold(true);
				$row++;
				//echo "<tr><td></td><td></td><th colspan=\"4\"><I><b>Total ".$detilL3->nama."</b></I></th><th align=right>Rp. ".number_format($jmlAkumL3,2,',','.')."</th><th > </th></tr>";
		}
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Total ".strtoupper($detil->nama))->getStyle('C'.$row)->getFont()->setSize(14);
			$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->setCellValue('H'.$row, "Rp. ".number_format($jmlLvl2,2,',','.'))->getStyle('H'.$row)->getFont()->setSize(14);
			$objPHPExcel->getActiveSheet()->getStyle('H'.$row)->getFont()->setBold(true);
			$row++;

		
		//echo "<tr><td></td><th colspan=\"5\"><b>Total ".strtoupper($detil->nama)."</b></th><th align=right >Rp. ".number_format($jmlLvl2,2,',','.')."</th><th > </th></tr>";
	}

//============================
$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, "AKTIFITAS INVESTASI")->getStyle('D'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('D'.$row)->getFont()->setBold(true);
$row++;
$rsJumlahBeliAset=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1  and id_cab=".$cab_pilih."  and idacc like '1-3%' and upper(nama) not like '%AKUM%') and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();
$jmlExpense=$jmlExpense+$rsJumlahBeliAset->jml;
$objPHPExcel->getActiveSheet()->setCellValue('E'.$row, "Pembelian Semua Aset Bersih")->setCellValue('F'.$row, " Rp. ".number_format($rsJumlahBeliAset->jml,2,',','.'));
$row++;
$rsJumlahKeluarInvestasi=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet in (select distinct idacc from ak_rekeningperkiraan where status=1  and id_cab=".$cab_pilih."  and idacc like '1-4%') and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();
$jmlExpense=$jmlExpense+$rsJumlahKeluarInvestasi->jml;
//$jumlahInvestasi=($rsJumlahModal->jml+$rsJumlahJualAset->jml)-($rsJumlahBeliAset->jml+$rsJumlahKeluarInvestasi->jml);
$objPHPExcel->getActiveSheet()->setCellValue('E'.$row, "Pengeluaran Investasi")->setCellValue('F'.$row, " Rp. ".number_format($rsJumlahKeluarInvestasi->jml,2,',','.'));
$row++;

$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, "Total Aktifitas Investasi")->getStyle('D'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('D'.$row)->getFont()->setBold(true);
$objPHPExcel->getActiveSheet()->setCellValue('E'.$row, "Rp. ".number_format(($rsJumlahBeliAset->jml+$rsJumlahKeluarInvestasi->jml),2,',','.'))->getStyle('E'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('E'.$row)->getFont()->setBold(true);
$row++;

//============================

	$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, "TOTAL BIAYA ")->getStyle('B'.$row)->getFont()->setSize(14);
	$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->setCellValue('I'.$row, "Rp. ".number_format($jmlExpense,2,',','.'))->getStyle('I'.$row)->getFont()->setSize(14);
	$objPHPExcel->getActiveSheet()->getStyle('I'.$row)->getFont()->setBold(true);
	$row+=2;

//echo "<tr><th></th><th colspan=\"5\"><b>TOTAL BIAYA</b></th><th align=right>Rp. ".number_format($jmlExpense,2,',','.')."</th><th > </th></tr>";
	
$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, "PENDAPATAN LAIN-LAIN ")->getStyle('B'.$row)->getFont()->setSize(14);
$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
$row++;
	$str="select * from ak_rekeningperkiraan where idparent='8-0000'  order by idacc ASC";	
	$resList= $this->db->query($str)->result();
	
	if (sizeof ($resList)<=0){
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Rekening Perkiraan Pendapatan Lain-lain Tidak ada");
		$row++;
		
	}else{
		
		foreach ($resList as $detil){	//lvl2
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $detil->nama)->getStyle('C'.$row)->getFont()->setSize(14);
			$objPHPExcel->getActiveSheet()->getStyle('C'.$row)->getFont()->setBold(true);
			$row++;		
			

			$strB="select * from ak_rekeningperkiraan where idparent='".$detil->idacc."'  order by idacc";	
			$resListB= $this->db->query($strB)->result();			
			foreach ($resListB as $detilB){		//level3	
				$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detilB->nama);
				$row++;		
				
				$strL3="select * from ak_rekeningperkiraan where idparent='".$detilB->idacc."' and id_cab=".$cab_pilih."  order by idacc";	
				$resList3= $this->db->query($strL3)->result();	
				
				$i=1;
				foreach ($resList3 as $detilLvl3){	//level4
					$strL4="select * from ak_rekeningperkiraan where idparent='".$detilLvl3->idacc."' and id_cab=".$cab_pilih."  order by idacc";	
					$resList4= $this->db->query($strL4)->result();	

					foreach ($resList4 as $detilLvl4){	//level5
						$rsJumlahKredit=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkkredit ='".$detilLvl4->idacc."' and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();
						$rsJumlahDebet=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet ='".$detilLvl4->idacc."' and bulan='$bln' and tahun='$thn' and status_validasi=1")->row();
						$jumlahPL=$rsJumlahKredit->jml - $rsJumlahDebet->jml;
						if ($jumlahPL>0){
							echo "<tr>";
							echo "<td></td>";
							echo "<td></td>";						
							echo "<td></td>";						
							echo "<td colspan=2>$i.&nbsp;".$detilLvl4->nama."</td>";			
							echo "<td align=right>Rp.&nbsp;".number_format($jumlahPL,2,',','.')."</td>";	
							echo "<td >&nbsp;</td>";
							echo "<td >&nbsp;</td>";
							echo "</tr>";
							
							$jmlIncomeLain2+=$jumlahPL;
							$jmlIncome+=$jumlahPL;
							$i++;
						}
						
					}
				}
			}
			
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row,"Sub Total ".$detil->nama)->getStyle('C'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->setCellValue('F'.$row, "Rp. ".number_format($jmlIncomeLain2->jml,2,',','.'))->getStyle('F'.$row)->getFont()->setBold(true);
			$row++;	

			/*echo "<tr>";
			echo "<td></td>";			
			echo "<td colspan=4><b>Sub Total ".$detilB->nama."</b></td>";
			echo "<td align=right>Rp. ".number_format($jmlIncomeLain2,2,',','.')."</td><td colspan=2></td>";
			echo "</tr>";*/
		}
		
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row,"Total Pendapatan Lain-lain ")->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->setCellValue('G'.$row, "Rp. ".number_format($jmlIncomeLain2->jml,2,',','.'))->getStyle('G'.$row)->getFont()->setBold(true);
		$row++;	

		$jumlahAnggaran+=$jmlIncomeLain2; 
		$objPHPExcel->getActiveSheet()->setCellValue('C'.$row,"Total Pendapatan Keseluruhan ")->getStyle('C'.$row)->getFont()->setBold(true);
		$objPHPExcel->getActiveSheet()->setCellValue('G'.$row, "Rp. ".number_format($jumlahAnggaran->jml,2,',','.'))->getStyle('G'.$row)->getFont()->setBold(true);
		$row+=2;	

	}
	
	//biaya lain2 9-1101
	$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, "BIAYA LAIN-LAIN")->getStyle('B'.$row)->getFont()->setSize(14);
	$objPHPExcel->getActiveSheet()->getStyle('B'.$row)->getFont()->setBold(true);
	$row++;	
	$strLain="select * from ak_rekeningperkiraan where idparent='9-1000'  order by  idacc";
	$resListLain= $this->db->query($strLain)->result();
	
		foreach ($resListLain as $detilLain){	
			$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, $detilLain->nama)->getStyle('C'.$row)->getFont()->setBold(true);
			$row++;
			
			$strLain2="select * from ak_rekeningperkiraan where idparent='".$detilLain->idacc."' and id_cab=".$cab_pilih." order by  idacc";
			$resListLain2= $this->db->query($strLain2)->result();
			
			foreach ($resListLain2 as $detilLain2){				
				$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $detilLain2->nama)->getStyle('D'.$row)->getFont()->setBold(true);
				$row++;
				
				$jmlLain=0;
				$i=1;
				$strLain3="select * from ak_rekeningperkiraan where idparent='".$detilLain2->idacc."'   order by  idacc";
				$resListLain3= $this->db->query($strLain3)->result();
				foreach ($resListLain3 as $detilLain3){
					$rsJumlahDebetBL=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkdebet ='".$detilLain3->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
					$rsJumlahKreditBL=$this->db->query("select ifnull(sum(jumlah),0) jml from jurnal where idperkkredit ='".$detilLain3->idacc."' and bulan='$bln' and tahun='$thn'  and status_validasi=1")->row();
					$jumlahBL=($rsJumlahDebetBL->jml) - $rsJumlahKreditBL->jml;					
					$jmlLain+=$jumlahBL;
					$jmlExpense+=$jumlahBL;					
					$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, $i)->setCellValue('E'.$row, $detilLain3->nama)->setCellValue('G'.$row, "Rp. ".number_format($jumlahBL,2,',','.'));
					$row++;
					$i++;
				}
			}
		}
	$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Total Biaya Lain-lain")->getStyle('C'.$row)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->setCellValue('F'.$row, "Rp. ".number_format($jmlLain,2,',','.'))->getStyle('F'.$row)->getFont()->setBold(true);
	$row++;
	//echo "<tr><td></td><th colspan=\"4\"><b>Total Biaya Lain-lain</b></th><th align=right>Rp. ".number_format($jmlLain,2,',','.')."</th><th colspan=2> </th></tr>";
	$saldo=$jumlahAnggaran-$jmlExpense;

	$objPHPExcel->getActiveSheet()->setCellValue('C'.$row, "Total Biaya Keseluruhan")->getStyle('C'.$row)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->setCellValue('G'.$row, "Rp. ".number_format($jmlExpense,2,',','.'))->getStyle('G'.$row)->getFont()->setBold(true);
	$row+=2;

	$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, "SALDO AKHIR BULAN")->getStyle('B'.$row)->getFont()->setBold(true);
	$objPHPExcel->getActiveSheet()->setCellValue('I'.$row, "Rp. ".number_format($saldo,2,',','.'))->getStyle('I'.$row)->getFont()->setBold(true);
	$row++;

		
		
		
		//END OF ISI

		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B $title &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
	
	
}
