<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class rptRekapJurnal extends MY_App {
	var $branch = array();
	function __construct()
	{
		parent::__construct();
		$this->load->model('report_model');
		$this->config->set_item('mymenu', 'menuLima');
		$this->config->set_item('mysubmenu', 'menuLima2');
		$this->load->helper('file');
		$this->load->library('CI_Pdf');
		$this->auth->authorize();
	}
	
	public function index()
	{	
		
		$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Rekap Jurnal</a></li>');
		$this->template->set('pagetitle','Filter Rekap Jurnal');		
		
		$data['arrBulan'] = $this->arrBulan2;
		$data['arrThn'] = $this->getYearArr();
		$data["jenis"]="rekapjurnal";
		$data["action"]="rptRekapJurnal/result";
		$this->template->load('default','freport/filter',$data);
	}
	
	
	public function result($param=null){
		$header=$this->commonlib->reportHeader();
		$footer=$this->commonlib->reportFooter();		
		$blnStr=$this->arrBulan2;
		
		if ($param!=null){
			$arr=explode("_",$param);
			$thn=$arr[0];
			$bln=$arr[1];
			$display=$arr[2];
			$sesLogin=$arr[3];
			$wilayah=$arr[4];
			
		}else{
			$sesLogin=$this->input->post('sesLogin');
			$display=$this->input->post('display');
			$thn=$this->input->post('cbTahun');
			$bln=$this->input->post('cbBulan');
		
			if ($sesLogin=='center'){
				$wilayah=$this->input->post('wilayah');
			}else{
				$wilayah=$this->session->userdata('auth')->ID_CABANG;
			}
		}
		$cab_2d="";
		if ($sesLogin=='center'){
			$cab_2d=(strlen($wilayah)<=1?"0".$wilayah:$wilayah);
		
		}	
		

		$title='Daftar Rekap Jurnal periode '.$blnStr[$bln].' - '.$thn;
		$data['title']=$title;
		$data['display']=$display;
		$data['thn']=$thn;
		$data['bln']=$bln;
		//$data['idacc']=$idacc;
		//$data['accName']=$accName;
		$data['sesLogin']=$sesLogin;		
		$data['wilayah']=$wilayah;
		
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$data['nmcabang']=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$namafile="rekapJurnal_".$thn."_".$bln;
		if ($display==0){
			$this->template->set('breadcrumbs','<li><a href="#">Laporan</a></li><li><a href="#">Bank Register</a></li>');
			$this->template->set('pagetitle',$title.' (View/Cetak)');		
			$this->template->load('default','freport/displayRekapJurnal',$data);
		}else{
			$html=$header;
			$html.=$this->load->view('freport/displayRekapJurnal', $data, true);
			$html.=$footer;
			//echo $html;
			$this->ci_pdf->pdf_create_report($html, $namafile, 'a4', 'portrait');
		}

	}
	
	
	public function toExcel(){
		$blnStr=$this->arrBulan2;
		$arr=explode("_",$this->input->post('param'));
		$tgl1=$arr[0];
		$tgl2=$arr[1];
		$display=$arr[2];			
		$idacc=$arr[3];	
		$sesLogin=$arr[4];
		if ($sesLogin=='center'){
			$wilayah=$arr[5];
		}
		$cab_pilih=($sesLogin=='center'?$wilayah:$this->session->userdata('auth')->ID_CABANG);
		$nmcabang=$this->gate_db->query("select KOTA from mst_cabang where ID_CABANG=".$cab_pilih)->row();
		$accName=$this->report_model->getAccName($idacc);

		$objPHPExcel = new PHPExcel();
		// Set document properties
		$objPHPExcel->getProperties()->setCreator("amanahsolution.com")
									 ->setLastModifiedBy("amanahsolution.com")
									 ->setTitle("Office 2007 XLSX Report Generator Document")
									 ->setSubject("Office 2007 XLSX Report Generator Document")
									 ->setDescription("Report Generator document for Office 2007 XLSX, generated by PHP classes.")
									 ->setKeywords("office 2007 openxml php")
									->setCategory("Report Generator Document");
		
		$objPHPExcel->setActiveSheetIndex(0);

		
		//logo
		$company=$this->session->userdata('param_company');
		$logo=$this->session->userdata('logo');
		$title='Bank Register '.$nmcabang->KOTA.' antara '.$tgl1." s.d ".$tgl2;
		$namafile="bankRegister_".$nmcabang->KOTA."_".$tgl1."_".$tgl2;

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('Logo');
		$objDrawing->setDescription('Logo');
		$objDrawing->setPath('assets/img/'.$logo);
		$objDrawing->setHeight(70);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(0);		
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

		 
		// Header
		$objPHPExcel->getActiveSheet()->mergeCells('C1:AF1');
		$objPHPExcel->getActiveSheet()->setCellValue('C1', $company);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setSize(20);
		$objPHPExcel->getActiveSheet()->getStyle('C1')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C2:AF2');
		$objPHPExcel->getActiveSheet()->setCellValue('C2', $title);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setSize(14);
		$objPHPExcel->getActiveSheet()->getStyle('C2')->getFont()->setBold(true);
		
		$objPHPExcel->getActiveSheet()->mergeCells('C3:AF3');
		$objPHPExcel->getActiveSheet()->setCellValue('C3', 'Diterbitkan Tgl :'.date('d F Y'));
		$objPHPExcel->getActiveSheet()->getStyle('C3')->getFont()->setSize(12);
			// Rename worksheet (worksheet, not filename)
		$objPHPExcel->getActiveSheet()->setTitle('BankRegister');

		//tambah cek idacc isparent?
		$strCek="select count(*) cek from ak_rekeningperkiraan where idparent='".$idacc."'";
		$resCek= $this->db->query($strCek)->row();	
		if ($resCek->cek<=0){
		$objPHPExcel->getActiveSheet()->setCellValue('B5', "[ ".$idacc." ] ".strtoupper($accName));

		$objPHPExcel->getActiveSheet()->setCellValue('B6', 'NO')
									->setCellValue('C6', 'TANGGAL')
									->setCellValue('D6', 'KETERANGAN')
									->setCellValue('E6', 'DEBET')
									->setCellValue('F6', 'KREDIT')
									->setCellValue('G6', 'SALDO');
		$objPHPExcel->getActiveSheet()->getStyle("B6:G6")->applyFromArray(
		array(
			'font'    => array(
				'bold'      => true
			),
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			),
			'borders' => array(
				'allborders'     => array(
 					'style' => PHPExcel_Style_Border::BORDER_THIN,
					'color' => array('argb' => '000000')
 				)				
			),
			'fill' => array(
	 			'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
	  			'rotation'   => 90,
	 			'startcolor' => array(
	 				'argb' => 'FFA0A0A0'
	 			),
	 			'endcolor'   => array(
	 				'argb' => 'FFFFFFFF'
	 			)
	 		)
		)
		);
	
$blnIdk=$this->arrIntBln;
//saldo bulan lalu = initval + bln-1
$initval=$this->report_model->getInitVal($idacc);
$saldoLalu=$this->report_model->getSaldoLaluWithInterval($idacc, $tgl1);
$jumlah=$initval+$saldoLalu;
$row=7; 
$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, '1')->setCellValue('C'.$row, '-')->setCellValue('D'.$row, 'Saldo Periode Lalu')	->setCellValue('E'.$row, ($jumlah>0?" Rp. ".number_format($jumlah,2,',','.'):"Rp. 0")   )->setCellValue('F'.$row, ($jumlah>0?"Rp. 0":" Rp. ".number_format($jumlah,2,',','.')))->setCellValue('G'.$row, " Rp. ".number_format($jumlah,2,',','.'));
$row++;
//current bln
$str="select * from ak_jurnal where (idperkdebet='$idacc' or idperkkredit='$idacc') and (tanggal>='$tgl1' and tanggal<='$tgl2') and status_validasi=1 order by tanggal";
$resList= $this->db->query($str)->result();
if (sizeof($resList )<=0){
	$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Belum ada transaksi atau transaksi belum divalidasi');
	 $row++;
}else{
	$i=2;
	foreach ($resList as $detil){
		//$jumlah=($detil->jenis=="BKM"?($jumlah+$detil->jumlah):($jumlah-$detil->jumlah));
		if ($detil->idperkdebet==$idacc){	//idacc debet
			$jumlah+=$detil->jumlah;
		}else{
			$jumlah-=$detil->jumlah;
		}
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $i)
										->setCellValue('C'.$row, strftime('%d %B %Y', strtotime($detil->tanggal)))
										->setCellValue('D'.$row, $detil->keterangan)
										->setCellValue('E'.$row, "Rp. ".($detil->idperkdebet==$idacc ?number_format($detil->jumlah,2,',','.'):0))
										->setCellValue('F'.$row, "Rp. ".($detil->idperkkredit==$idacc ?number_format($detil->jumlah,2,',','.'):0))
										->setCellValue('G'.$row, " Rp. ". ($jumlah<=0?"( ".number_format(($jumlah*-1),2,',','.')." )":number_format($jumlah,2,',','.')));
				
		$i++;
		$row++;
		}
	}
	$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, 'Saldo Akhir Kas')->setCellValue('G'.$row, " Rp. ".number_format($jumlah,2,',','.'));
			$objPHPExcel->getActiveSheet()->getStyle('D'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->getStyle('G'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->getStyle('B'.$row.':G'.$row)->applyFromArray(
				array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				)
				);
	

} else{
	$strSub="select * from ak_rekeningperkiraan where idparent='".$idacc."'";
	$resSub= $this->db->query($strSub)->result();

			//menghitung total parent
			$jumlahParentTotal=0;
			foreach ($resSub as $detilresSub){
				$initval=$this->report_model->getInitVal($detilresSub->idacc);
				$saldoLalu=$this->report_model->getSaldoLaluWithInterval($detilresSub->idacc, $tgl1);
				$jumlahParent=$initval+$saldoLalu;

				$strJurnalParent="select * from ak_jurnal where (idperkdebet='$detilresSub->idacc' or idperkkredit='$detilresSub->idacc') and (tanggal>='$tgl1' and tanggal<='$tgl2') and status_validasi=1  order by tanggal";
				$resListJurnalParent= $this->db->query($strJurnalParent)->result();
				$debetParent=0;
				$kreditParent=0;
				if (sizeof($resListJurnalParent )<=0){
					//echo "<tr><td colspan=6 style=\"text-align:center\">Belum ada transaksi </td></tr>";
				}else{
					foreach ($resListJurnalParent as $detilJurnalParent){
						if ($detilJurnalParent->idperkdebet==$detilresSub->idacc){
								//echo number_format($detilJurnalParent->jumlah,2,',','.');
								$jumlahParent+=$detilJurnalParent->jumlah;
								$debetParent+=$detilJurnalParent->jumlah;
						}
						if ($detilJurnalParent->idperkkredit==$detilresSub->idacc){
								//echo number_format($detilJurnalParent->jumlah,2,',','.');
								$jumlahParent-=$detilJurnalParent->jumlah;
								$kreditParent+=$detilJurnalParent->jumlah;
						}
						

					}

				}
				$jumlahParentTotal+=$jumlahParent;

			}

	$objPHPExcel->getActiveSheet()->setCellValue('B5', "[ ".$idacc." ] ".strtoupper($accName))->setCellValue('G5',"   Rp. ".number_format($jumlahParentTotal,2,',','.'));

	
	$row=8;
	foreach ($resSub as $detilresSub){	//loop lvl anak
		$idaccsub=$detilresSub->idacc;
		$accNameDetSub=$this->report_model->getAccName($idaccsub);	 

		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, "[ ".$idaccsub." ] ".strtoupper($accNameDetSub));
		$row++;
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'NO')
									->setCellValue('C'.$row, 'TANGGAL')
									->setCellValue('D'.$row, 'KETERANGAN')
									->setCellValue('E'.$row, 'DEBET')
									->setCellValue('F'.$row, 'KREDIT')
									->setCellValue('G'.$row, 'SALDO');
		$objPHPExcel->getActiveSheet()->getStyle('B'.$row.':G'.$row)->applyFromArray(
		array(
			'font'    => array(
				'bold'      => true
			),
			'alignment' => array(
				'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
			),
			'borders' => array(
				'allborders'     => array(
 					'style' => PHPExcel_Style_Border::BORDER_THIN,
					'color' => array('argb' => '000000')
 				)				
			),
			'fill' => array(
	 			'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
	  			'rotation'   => 90,
	 			'startcolor' => array(
	 				'argb' => 'FFA0A0A0'
	 			),
	 			'endcolor'   => array(
	 				'argb' => 'FFFFFFFF'
	 			)
	 		)
		)
		);
$row++;	
$blnIdk=$this->arrIntBln;
//saldo bulan lalu = initval + bln-1
$initval=$this->report_model->getInitVal($idaccsub);
$saldoLalu=$this->report_model->getSaldoLaluWithInterval($idaccsub, $tgl1);
$jumlah=$initval+$saldoLalu;

$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, '1')->setCellValue('C'.$row, '-')->setCellValue('D'.$row, 'Saldo Periode Lalu')	->setCellValue('E'.$row, ($jumlah>0?" Rp. ".number_format($jumlah,2,',','.'):"Rp. 0")   )->setCellValue('F'.$row, ($jumlah>0?"Rp. 0":" Rp. ".number_format($jumlah,2,',','.')))->setCellValue('G'.$row, " Rp. ".number_format($jumlah,2,',','.'));

$row++;	

$str="select * from ak_jurnal where (idperkdebet='$idaccsub' or idperkkredit='$idaccsub') and (tanggal>='$tgl1' and tanggal<='$tgl2') and status_validasi=1 order by tanggal";
$resList= $this->db->query($str)->result();
if (sizeof($resList )<=0){
	$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, 'Belum ada transaksi atau transaksi belum divalidasi');
	$row++;
}else{
	$i=2;
	foreach ($resList as $detil){
		if ($detil->idperkdebet==$idaccsub){	//idacc debet
			$jumlah+=$detil->jumlah;
		}else{
			$jumlah-=$detil->jumlah;
		}
		$objPHPExcel->getActiveSheet()->setCellValue('B'.$row, $i)
										->setCellValue('C'.$row, strftime('%d %B %Y', strtotime($detil->tanggal)))
										->setCellValue('D'.$row, $detil->keterangan)
										->setCellValue('E'.$row, "Rp. ".($detil->idperkdebet==$idaccsub ?number_format($detil->jumlah,2,',','.'):0))
										->setCellValue('F'.$row, "Rp. ".($detil->idperkkredit==$idaccsub ?number_format($detil->jumlah,2,',','.'):0))
										->setCellValue('G'.$row, " Rp. ". ($jumlah<=0?"( ".number_format(($jumlah*-1),2,',','.')." )":number_format($jumlah,2,',','.')));
				
		$i++;
		$row++;
		}
	}
	$objPHPExcel->getActiveSheet()->setCellValue('D'.$row, 'Saldo Akhir Kas')->setCellValue('G'.$row, " Rp. ".number_format($jumlah,2,',','.'));
			$objPHPExcel->getActiveSheet()->getStyle('D'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->getStyle('G'.$row)->getFont()->setBold(true);
			$objPHPExcel->getActiveSheet()->getStyle('B'.$row.':G'.$row)->applyFromArray(
				array(
					'font'    => array(
						'bold'      => true
					),
					'alignment' => array(
						'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
					),
					'borders' => array(
						'allborders'     => array(
							'style' => PHPExcel_Style_Border::BORDER_THIN,
							'color' => array('argb' => '000000')
						)				
					),
					'fill' => array(
						'type'       => PHPExcel_Style_Fill::FILL_GRADIENT_LINEAR,
						'rotation'   => 90,
						'startcolor' => array(
							'argb' => 'FFA0A0A0'
						),
						'endcolor'   => array(
							'argb' => 'FFFFFFFF'
						)
					)
				)
				);

			$row+=2;
			

	 }
}

		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddHeader('&L&B $title &RPrinted on &D');
		$objPHPExcel->getActiveSheet()->getHeaderFooter()->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');

		// Set page orientation and size
		//echo date('H:i:s') , " Set page orientation and size" , EOL;
		$objPHPExcel->getActiveSheet()->getPageSetup()->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_PORTRAIT);
		$objPHPExcel->getActiveSheet()->getPageSetup()->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
		// Redirect output to a client’s web browser (Excel2007)
		//clean the output buffer
		ob_end_clean();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('assets/report/'.$namafile.'.xlsx');
		//write_file($path."/".$fileName,$out);
		$data['isi']="assets/report/".$namafile.".xlsx";
		echo json_encode($data);
		
	}
	
}
